### ISSUE TITLE
Overall review

### ISSUE THREAD

**Issue by ar-mac** [Fafruch/kalkulator-agh#2]
1. Most popular and widely used boilerplate for setting up react app is [create-react-app](https://github.com/facebookincubator/create-react-app). For starting next projects consider using it.

------------

2. For merging objects use spread operator, and provide only updated values, as it's more concise and less error prone.
subjects.js
```
case 'TOGGLE_SUBJECT':
  return state.map(
    subject => (subject.id === action.id) ? {
      ...subject,
      active: !subject.active
    }
    : subject
  )
```
-------------

3. Create actions according to [standard flux action](https://redux-actions.js.org/docs/api/createAction.html#createactiontype-payloadcreator-metacreator) structure. 
```
{
  type: UPDATE_SUBJECT,
  payload: {id, name, elementaryScore, advancedScore}, // all relevant data should be under payload key
  meta: {error: ''}, // if you have to provide metadata
}
```
Also this redux-actions package is worth checking out

-----------

4. Use and know about automatic [type coercion](http://speakingjs.com/es5/ch08.html#type_coercion)
`if (advancedScore !== 0)` shorter version `if (advancedScore)`
and in other places

---------

5. Object/array mutation is not reassignment, so `const` can be used instead of `let` for them in most of the cases. Check `scoreObject, formInput`

also `scoreA` is not modified and should be set as `const`.

--------

6. Popular practice is to keep external and internal imports grouped and separated with empty line.

--------

7. Constants in SubjectTypes are not used for display purposes and should have english values. Also name them using UPPER_SNAKE_CASE convention.

--------

8. Usage of fat arrow functions allows more concise syntax
```
const mapStateToProps = (state) => ({
  subjects: state.subjects
});
```

-------

9. check bulk binding of actionCreators
```
const mapDispatchToProps = (dispatch) => bindActionCreators({
    onChange: updateSubject,
    onToggleClick: toggleSubject,
    onDelete: removeSubject,
}, dispatch);
```

--------

10. In AddSubjectToContainer bind `addSubject` action with `mapDispatchToProps` instead of dispatching it inside component to keep consistency with other containers. (Also using mapDispatchToProps is cleaner and more widely used)

--------

11. Subjects with different types should be passed to the list component separately to prevent iterating over all elements and returning markup only for the ones with matching `type`. (SubjectList.jsx)

This can be achieved in (at least) two ways.
- Keep subjects in separate lists in store, and in 'mapStateToProps' select proper list using `subjectsType` provided from parent component.
This way is useful when there is hard division between data groups (in this case type is such hard division).
```
{
  subjects: {
    main: [{}]
    lingual: [{}, {}],
  }
}
```
- Other way is: in `mapStateToProps` use [selector](https://egghead.io/lessons/javascript-redux-filtering-redux-state-with-react-router-params) to filter subjects according to `subjectsType` provided from parent component.
This method is useful when division is light and dynamic. eg. Using selector to get subjects with elementary score over 80 threshold or something like that.

--------

12. Optimization
```
<Subject
  id={subject.id}
  name={subject.name}
  elementaryScore={subject.elementaryScore}
  advancedScore={subject.advancedScore}
  active={subject.active}
  onChange={onChange}
  onToggleClick={onToggleClick}
  onDelete={onDelete}
  subjectsType={subjectsType}
/>
```
more concise version
```
<Subject
  {...subject}
  onChange={onChange}
  onToggleClick={onToggleClick}
  onDelete={onDelete}
  subjectsType={subjectsType}
/>
```
also why not pass the whole subject and destructure it inside `Subject`
```
<Subject
  subject={subject}
  onChange={onChange}
  onToggleClick={onToggleClick}
  onDelete={onDelete}
  subjectsType={subjectsType}
/>
```

-------

13. Table setup and header should be in SubjectsList and Subject would only render `tr` with relevant data. Currently every Subject has its own table with legend which is unnecessary duplication.

-------

14. Use string interpolation
`elementaryScore + '%'` ` `${elementaryScore}%` `

------

15. optimization
`parseInt(formInput.advancedScore.value, 10)` shorter version `+formInput.advancedScore.value`
[type coertion](https://medium.com/@nikjohn/cast-to-number-in-javascript-using-the-unary-operator-f4ca67c792ce)

------

**Due to late hour I'll stop review, and provide the rest of it tomorrow, for calculator container, its children & used services.**

Anyway good job. It's not commertial grade quality, but you'll get there sooner than later. 😄 👍

**Comment by Fafruch** [comment]
1. I've chosen this one cause it contained all the modules I needed like Redux and React Hot Loader (but at the same time many of them I don't need). Next time I will try yours :)

---
2. This seemed not to work in UPDATE_SUBJECT so I gave up this syntax, but code looks different there: 
``` 
case 'UPDATE_SUBJECT':
      return state.map(
        subject => (subject.id === action.id) ? {
          id: action.id,
          name: action.name,
          type: subject.type,
          elementaryScore: action.elementaryScore,
          advancedScore: action.advancedScore,
          active: subject.active
        }
        : subject
      )
```
But in TOGGLE_SUBJECT it works. Thanks :)

---
3. Didn't know that convention. I'll try to rewrite it

---
4. My idea was to make these comparisons explicit. Should I also change eg. 
` if (maxScoreWrapper === null)` to ` if (!maxScoreWrapper)`?

---
5. Right! I'll fix that.

---
6. The same.

---
7. Good point. :) What I have is `<Subjects subjectsType={primarySubjects} />` and `export const primarySubjects = 'Główne'`. At first I had `<Subjects subjectsType='Główne' />` just to distinguish two separate components with the same functionality, but I didn't want these ugly polish strings in code so I moved them to constants. But as you mentioned, their values are never used. So is there any elegant way to make use of only the keys and get rid of the values like 'Główne' and 'Językowe'?

---
8. To fix. :)

---
9. Ok! BTW:
```
let SubjectListContainer = ({ subjectsType }) => (
  <SubjectList subjectsType={subjectsType} />
)
```
 Is there any better way to pass props to wrapped components and remove this piece of code? ESLint doesn't like this idea and asks for required actionCreators not passed the same way (cause they are injected with connect).

---
10. Yeah, surely this will make code more consistent. :)

---
11. That's a very good idea! The first approach seems to be very intuitive when you think about the composition of state. Anyway it's a bit tricky and looks like it'll need more code changes, but will try to resolve it soon :)

---
12. I knew there's some kind of syntactic sugar for that but I couldn't find it. Thanks a lot. :)

---
13. I intended to treat every subject's representation as separate table with its own contents

---
14. Are there any benefits in using string interpolation here? I ask out of curiosity

---
15. Wow, this looks cool!

---
16. In conclusion, thanks a lot for your help. :) I really really appreciate that!

**Comment by ar-mac** [comment]
DISCLAIMER: Review I provide is my way of doing things according to my current knowledge. It's not "The Best and Only Way"™
So take what you find useful and if you don't feel something, then choose your own way.
I'm kind of perfectionist so most of the things I cover are tiny details which are not necessarily critical. Nonetheless they are a good occasion to learn and improve and if you early adapt good practices, the better 😄 

I'll start with responding to your response 😄 

------

1. This is not actually 'mine', but it's most widely used boilerplate, also maintained by creators of react.
Also you can try to make your setup from scratch, as such digging in nuts & bolts will make you learn lots of things and how is it all wired up together.

-----

2. I'm curious how destructuring was not working for UPDATE_SUBJECT. Could you provide code which  you tried? We'll figure out what was the problem, as for me there is no reason for this to not work.

-----

4. Sure they are explicit, but leveraging type coercion in conditionals is widely used on daily basis.
Yes, you definitely should change other usages. 👍 

-----

7. Yes there is. Check [Symbol](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol)
```
const PRIMARY_SUBJECT = Symbol();
const LINGUAL_SUBJECT = Symbol();
```
Actually I haven't seen this being used in production applications, but I think It's marginally better than
`const PRIMARY_SUBJECT = 'PRIMARY_SUBJECT';` which is pattern I see everywhere.

-----

9. In one application we have removed `.isRequired` from params passed from `connect`, for exactly same reason you provided ;)
You can try setting separate propTypes for wrapper and container which will match actual props being passed. Tell me how this worked for you (PR? 😄 )

-----

11. Changing state format definitely will require multiple changes all over the app.
If you'll apply them, using `ownProps` might get handy for getting proper subjects from store.
```
const mapStateToProps = (state, ownProps) => ({
  subjects: state.subjects[ownProps.subjectsType],
})
```

-----

14. There are multiple benefits 😄 
- String is one entity.
- You can see where it starts and ends just by looking at \` symbol. 
- Editor can help you select this string (not possible when constructing it using `+`)
- Using interpolation discourages constructing string in different parts of the code before final display/usage. You have to put all pieces at the same time.

-----

17. In Calculator.js
If `maxPrimaryScoreWrapper` returns `{computedScore: 0}` when subjectArray is empty you could replace
```
let maxPrimaryScoreWrapper = subjectPicker(subjects, primarySubjects)
let maxPrimaryScore
if (maxPrimaryScoreWrapper === null) maxPrimaryScore = 0
else maxPrimaryScore = maxPrimaryScoreWrapper.computedScore
```
with
```
const maxPrimaryScoreWrapper = subjectPicker(subjects, primarySubjects);
const maxPrimaryScore = maxPrimaryScoreWrapper.computedScore;
```
or even
`const {computedScore: maxPrimaryScore} = subjectPicker(subjects, primarySubjects);`
If you don't know what's going on, check my presentation about destructuring. (I have sent invitation to your github connected email)

General rule of thumb for using your own services, is to provide such api, that handling every response is as easy as possible.
In this case, when everything works fine it returns `{computedScore: value}`, but with fail, you returned `null` which required separate handling. Returning `{computedScore: 0}` is semantically correct, as thats what you actually do at `if (maxPrimaryScoreWrapper === null) maxPrimaryScore = 0` when there was no subjects.
Different story would be if empty subjectArray would be something really bad. Then go for throwing errors instead of "covering it" with defaults.

------

18. Obsolete else when if statement with return inside.
When `if` executes further code will not be evaluated. (Also occurs in subjectPicker.js)
```
if (maxPrimaryScoreWrapper === null && maxLingualScoreWrapper === null) return null
else return (<div>some markup</div>)
```
could be
```
if (maxPrimaryScoreWrapper === null && maxLingualScoreWrapper === null) return null
// here be some further computations evaluated only when conditional is false
return (<div>some markup</div>)
```

BTW
`if (!maxPrimaryScoreWrapper && !maxLingualScoreWrapper) return null`
Would have side effect, that MaxScore would not appear if both values are 0 which is good thing I guess.

BTW2 you can remove this main conditional and hide only specific subject groups when they have no points. This way you would not need to `if (maxScoreWrapper === null) return null` in BestSubject.js
```
return (
  <div className='m-4'>
    <h3>Wynik</h3>
    <hr />
    {maxPrimaryScore && <BestSubject
      maxScoreWrapper={maxPrimaryScoreWrapper}
      subjectType={primarySubjects}
    />}
    {maxLingualScore && <BestSubject
      maxScoreWrapper={maxLingualScoreWrapper}
      subjectType={lingualSubjects}
    />}
    <br />
    <MaxScore
      maxPrimaryScore={maxPrimaryScore}
      maxLingualScore={maxLingualScore} />
  </div>
)
```

------

19. Type coertion for string
`{maxScoreWrapper.subject.name === '' ? 'bez nazwy' : maxScoreWrapper.subject.name}`
can be
`{maxScoreWrapper.subject.name ? maxScoreWrapper.subject.name : 'bez nazwy'}`
or even
`{maxScoreWrapper.subject.name || 'bez nazwy'}`

-----

20. subjectPicker can be selector. Benefits:
- component receives `maxPrimaryScoreWrapper` straight from props and does not call `subjectPicker` by itself.
- this is easier to debug, as you just check what was passed to props
- testing this component would be much easier, as you could just render it with different props used by it directly. (currently you would need to set subjects data accordingly to subjectPicker implementation, so it returns specific `maxPrimaryScore` value)
- as you can see `subjects` property is not used by `Calculator` directly, but they need to be digested by subjectPicker.

Here the rule of thumb is:
When component receives some props only to pass it somewhere else and use returned data, then converting the data should be done somewhere else. (In selector if the data comes from store, or in parent/higher order component if it is not from store). That way every component receives only relevant data.

-----

21. PointsCalculator should handle multiplication of points for primary subject as this is his responsibility
```
if (subjectsType === primarySubjects) maxScoreWrapper.computedScore = maxScoreObj.computedScore * 4
  else maxScoreWrapper.computedScore = maxScoreObj.computedScore
```

-----

22. subjectPicker & points calculator can be simplified. (Lots of small little things, so that's how I would do them)
```
import pointsCalculator from './pointsCalculator'

const subjectPickerUtil = (subjects, subjectsType) => {
  let maxScoreWrapper = {
    subject: {},
    computedScore: 0,
    formula: ''
  }

  const subjectsArray = subjects.filter(subject => subject.active && (subject.type === subjectsType))

  return subjectsArray.reduce((currentMaxWrapper, subject) => {
    const currentScoreObj = pointsCalculator(subject)

    return (currentScoreObj.computedScore > currentMaxWrapper.computedScore)
      ? { ...currentScoreObj, subject }
      : currentMaxWrapper
  }, maxScoreWrapper)
}

export default subjectPickerUtil
```

pointsCalculator.js
```
import { PRIMARY_SUBJECT } from '../constants/SubjectTypes'

const pointsCalculator = ({ elementaryScore, advancedScore, type }) => {
  let scoreObj = {
    computedScore: 0,
    formula: '',
  }

  const scoreA = elementaryScore + advancedScore
  let scoreB = 0

  // no changes

  if (type === PRIMARY_SUBJECT) scoreObj.computedScore *= 4

  return scoreObj
}

export default pointsCalculator
```

-----

23. modules naming convention

- utility functions have names with lowerCamelCase saying what they do, so `pointsCalculator` should be `calculatePoints` or `getSubjectScore`

- utility objects/classes are named with UpperCamelCase saying what they are. eg. `PointsCalculator`

-----

Man, this was a lot of things to cover. :smile:
Hope my feedback was somewhat helpful.

-----

Extras:

24. Props for using arrayOf & shape PropTypes :+1:
25. Also where did you found the pattern for container components, for example `SubjectsList`? I haven't seen such way of doing them.

**Comment by Fafruch** [comment]
Before I rise to other numbers, I need to share my thoughts about the 11th. 

So the idea is to have the state tree as following:
```
{
  subjects: {
    main: [{}]
    lingual: [{}, {}],
  }
}
```

Then we need: 
```
export const makeRootReducer = (asyncReducers) => {
  return combineReducers({
    subjects: combineReducers({
      primary,
      lingual
    }),
    ...asyncReducers
  })
}
```

Problem appers with actionCreators and reducers (a lot of boilerplate code!) 


1. Then I have:

constants:
```
export const ADD_PRIMARY_SUBJECT = 'ADD_PRIMARY_SUBJECT'
export const ADD_LINGUAL_SUBJECT = 'ADD_LINGUAL_SUBJECT'
```

actionCreators:
```
export const addPrimarySubject = () => ({
  type: ADD_PRIMARY_SUBJECT,
  payload: {
    id: v4()
  }
})

export const addLingualSubject = () => ({
  type: ADD_LINGUAL_SUBJECT,
  payload: {
    id: v4()
  }
})
```

reducer:
```
export const primary = (state = [], action) => {{
  switch (action.type) {
    case ADD_PRIMARY_SUBJECT:
      return [
        ...state,
        {
          id: action.payload.id,
          name: '',
          elementaryScore: 0,
          advancedScore: 0,
          active: true
        }
      ]
...

export const lingual = (state = [], action) => {{
  switch (action.type) {
    case ADD_LINGUAL_SUBJECT:
      return [
        ...state,
        {
          id: action.payload.id,
          name: '',
          elementaryScore: 0,
          advancedScore: 0,
          active: true
        }
      ]
...
```

and then eg. AddSubjectContainer to be the same plus (for example): 
```
const mapDispatchToProps = (dispatch, ownProps) => {
  if (ownProps.subjectsType === PRIMARY_SUBJECTS) {
    return { onAdd: bindActionCreators(addPrimarySubject, dispatch) }
  }
  return { onAdd: bindActionCreators(addLingualSubject, dispatch) }
}
```

2. or have only one type of constants, actionCreators, reducers and have to provide subjectsType to every action:

```
export const addSubject = (subjectsType) => ({
  type: ADD_SUBJECT,
  payload: {
    id: v4(),
    subjectsType
  }
})
```

and need this ugly if statement to split two reducers from doing the same on every dispatch:

```
export const primary = (state = [], action) => {
  if (action.payload && action.payload.subjectsType === PRIMARY_SUBJECTS) {
    switch (action.type) {
      case ADD_SUBJECT:
        return [
          ...state,
          {
            id: action.payload.id,
            name: '',
            elementaryScore: 0,
            advancedScore: 0,
            active: true
          }
        ]
...

export const lingual = (state = [], action) => {
  if (action.payload && action.payload.subjectsType === LINGUAL_SUBJECTS) {
    switch (action.type) {
      case ADD_SUBJECT:
        return [
          ...state,
          {
            id: action.payload.id,
            name: '',
            elementaryScore: 0,
            advancedScore: 0,
            active: true
          }
        ] 
...
```

So it means a lot of similar code which certainly isn't DRY. Maybe there is some sleek way for that, but I don't see it now. :(

**Comment by Fafruch** [comment]
1. Yup!

---
2. I didn't understand destructuring yet. So I was trying to convert this: 
```
            id: action.payload.id,
            name: action.payload.name,
            type: subject.type,
            elementaryScore: action.payload.elementaryScore,
            advancedScore: action.payload.advancedScore,
            active: subject.active
```

to something like this: 
```
            ...subject,
            name: action.payload.name,
            ...subject,
            elementaryScore: action.payload.elementaryScore,
            advancedScore: action.payload.advancedScore,
            ...subject
```
:D That couldn't have worked.

---
7. I Finally used 
`const PRIMARY_SUBJECT = 'primary'` as it was a proper key in state.subjects[] in my attempts with changed structure of the tree. But probably this is out of convention. 

---
9. I didn't know that before - placing the wrapped component inside the container is redundant. I realised that passing props to container automatically passes them deeper - the wrapped one gets them. So I think it's how it should be done. 

---
14. Good to know. :) I will use it then

---
17. This makes a lot of sense. I got little experience with such APIs, so I am reinventing the wheel often. 

---
18. 
```
return (
    {maxPrimaryScore && <BestSubject
      maxScoreWrapper={maxPrimaryScoreWrapper}
      subjectType={primarySubjects}
    />}
```
This generated in HTML `0` or the component. I suppose it should return null or the component, but it didn't, so I changed it to ternary and it works: 
```
{maxPrimaryScore
      ? <BestSubject
        maxScoreWrapper={maxPrimaryScoreWrapper}
        subjectType={PRIMARY_SUBJECTS}
      />
      : null}
```

---
19. You're right!

---
20. What is the definition of selector? Do you mean something like https://github.com/reactjs/reselect ?

---
21. Good point!

---
22. I changed that, because I really like the idea of using reduce here, but on the other hand now I'm not able to hide MaxScore component when no subject is present. I must inform Calculator component that array is empty if I want to hide this component before adding any subject. So can I place this info inside 'formula'? So it would be eg. 'NO_SUBJECTS'.

---
23. Thanks, didn't know that. :) 

---
25. I think I was trying to imitate the redux examples from http://redux.js.org/docs/basics/ExampleTodoList.html

---
And thanks again for your help. :) Yes, it is very helpful, you don't know how much!

**Comment by ar-mac** [comment]
Regarding splitting subjects tree.

Despite having `main` & `lingual` under separate keys, they are basically the same entity - Subject. Only difference is type, apart from that they do not behave differently or anything. Which means that they can and should be handled by one `subjects` reducer.

To fix this ugly reducers you need to figure out way to use only one which will save new subject under proper key according to `action.payload.subjectsType`. Additional requirement is not to use `if` statements but only destructuring. I won't provide solution yet, so you can figure this by yourself. 😄 

-----

2. That makes sense it does not work.
If I translate destructured version into ES5 it would look like this

```
// destructured ...subject
  id: subject.id,
  name: subject.name,
  type: subject.type,
  elementaryScore: subject.elementaryScore,
  advancedScore: subject.advancedScore,
  active: subject.active,
  
  name: action.payload.name, // provided manually

  // destructured ...subject overrides name: action.payload.name 
  id: subject.id,
  name: subject.name,
  type: subject.type,
  elementaryScore: subject.elementaryScore,
  advancedScore: subject.advancedScore,
  active: subject.active,
  
  elementaryScore: action.payload.elementaryScore, // provided manually
  advancedScore: action.payload.advancedScore, // provided manually

  // destructured ...subject overrides all previous data
  id: subject.id,
  name: subject.name,
  type: subject.type,
  elementaryScore: subject.elementaryScore,
  advancedScore: subject.advancedScore,
  active: subject.active
```
In destructuring order is important, as the keys are applied from the first to the last, so defaults should be on the beginning, and overrides afterwards. Also I won't provide solution. hope you'll figure this by yourself.
TIP - you can also destructure `action.payload` as it's keys match exactly to the ones of updated subject.

------

7. `PRIMARY_SUBJECT = 'primary'` this is ok, and nice reuse of this as key in store 👍 

-----

9. Right, That's something new also for me, as I have used different pattern for container components.
Anyway this solution is good.

-----

18. Right, I forgot to prevent such situation.
There is no need for ternary. You can just use type coertion to transform `0` into `false` .
It's safer to always coerce in such situations to prevent displaying 0.
```
{!!maxPrimaryScore && <BestSubject
  maxScoreWrapper={maxPrimaryScoreWrapper}
  subjectType={primarySubjects}
/>}
```

-----

20. Reselect is a wrapper, which adds additional features to regular selectors. And that's not necessary to have it.
Selector is basically a function which receives store or it's fragment and extracts/transforms the data so it matches our components needs. 
In case of subjectPicker it receives store and subjectType and returns the wrapper for highest score in group.

CalculatorContainer.js
```
const mapStateToProps = (state) => {
  maxPrimaryWrapper: subjectPicker(state, PRIMARY_SUBJECT),
  maxLingualWrapper: subjectPicker(state, LINGUAL_SUBJECT),
};
```

------

22. Having `NO_SUBJECTS` is also a solution, or you can just add `isEmpty` key with values for both situations to returned wrapper.

-----

25. Thanks. There are so many ways to do stuff in react 😄 

-----

No problem. It's nice to talk with somebody who is eager to learn and improve. Also I find out about something new during the process. 💯

**Comment by Fafruch** [comment]
```
const subjects = (state = { primary: [], lingual: [] }, action) => {
  switch (action.type) {
    case ADD_SUBJECT:
      return {
        [action.payload.subjectsType]: [
          {
            id: action.payload.id,
            name: '',
            type: action.payload.subjectsType,
            elementaryScore: 0,
            advancedScore: 0,
            active: true
          },
          ...state[action.payload.subjectsType]
        ],
        ...state
      }
    case TOGGLE_SUBJECT: ...
...
```
I stuck with this piece of code. I believe it should look something like that, but unfortunately this doesn't work.

---
2. I see. I've already done that in awaiting PR, but didn't know how it is transpiled to ES5 JavaScript. Now it makes more sense. :)

---
20. Ok! 

---
22. Finally I used `isEmpty` but is that ok if it's a boolean and not a a function, so `isEmpty()`?

**Comment by ar-mac** [comment]
*. Yup, this won't work due to the same reason `UPDATE_SUBJECT` didn't work. You need to remember about the order of applying destructuring. For object destructuring further entries override previous.

Below simplified result of destructuring you provided, assuming action.payload.subjectsType is `'primary'`
```
{
  primary: [
    {}, // new subject
    {},{},{},{},{} // already existing subjects destructured from state[action.payload.subjectsType] array
  ],
  primary: [ // destructured from ...state, overrides previous `primary` key
    {},{},{},{},{} // already existing primary subjects
  ],
  lingual: [ // destructured from ...state
    {},{},{} // already existing lingual subjects
  ]
}
```

----

22. It should be boolean according to naming convention.

`isEmpty`: bool - because isEmpty is question about `state`

`getIsEmpty`, `checkIsEmpty`, `checkEmptiness`: function returning bool - because these are descriptions of doing something in order to find out what is the `state`.

In some applications you might find different conventions and in such cases you should apply to them for consistency. In other cases I think the one above is pretty clear and logical.

**Comment by Fafruch** [comment]
OMG, I'm so stupid. I spent so much time in front of the screen and haven't noticed that. Many thanks, man! Of course it was in wrong order.

---
22. These conventions make a lot of sense, good to know about them.

Now I need to rewrite the rest, I think it won't be difficult.

**Comment by ar-mac** [comment]
😄   No need for bashing yourself. Everyone makes mistakes, even such basic ones. Second pair of eyes is always useful.

Anyway good job with that destructuring 👍
