### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by dfelczak** [Fafruch/kalkulator-agh#3]
https://github.com/Fafruch/kalkulator-agh/blob/master/src/components/Calculator/MaxScore.js#L5
Go for consts. Make consts instead of let/var whenever possible. 

https://github.com/Fafruch/kalkulator-agh/blob/master/src/components/Calculator/Calculator.js#L14
You don't need comparing variables to null/undefined in JS. Also I'm sure you can simplify those conditions.

https://github.com/Fafruch/kalkulator-agh/blob/master/src/components/Calculator/Calculator.js#L6
Go for [webpack module resolving](https://webpack.github.io/docs/resolving.html)

https://github.com/Fafruch/kalkulator-agh/blob/master/src/components/Calculator/Calculator.js#L20
You don't need else statement 
```
() => {
  if(foo) {
     return bar;
  }
  return bar2;
}
```

https://github.com/Fafruch/kalkulator-agh/blob/master/src/components/Calculator/Calculator.js#L28
Please use ESLint with Airbnb-base plugin in next project. 

https://github.com/Fafruch/kalkulator-agh/blob/master/src/components/Subjects/Subject.js#L54
You don't need parseInt() for that. [Just use unary + operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Arithmetic_Operators#Unary_plus_(.2B) )

https://github.com/Fafruch/kalkulator-agh/blob/master/src/components/Subjects/Subject.js#L69
You don't need comparing variables to 0 or 1. [Type conversion in JavaScript](http://jibbering.com/faq/notes/type-conversion/)

https://github.com/Fafruch/kalkulator-agh/blob/master/src/components/Subjects/SubjectList.js#L14
Do not keep such comments in code. The information about key is obvious.

https://github.com/Fafruch/kalkulator-agh/blob/master/src/components/Subjects/SubjectList.js#L27
You don't need pass `iterator (i++)` into component. Go for [map](https://developer.mozilla.org/pl/docs/Web/JavaScript/Referencje/Obiekty/Array/map) index 

https://github.com/Fafruch/kalkulator-agh/blob/master/src/utils/subjectPicker.js#L35
Do not change objects after construction.
Objects are references, if we avoid changing their properties we avoid situation of unclear state. Also our finished code will be simpler to understand and easier to test.

https://github.com/Fafruch/kalkulator-agh/blob/master/src/utils/localStorage.js#L12
You don't need return undefined in function. Function without `return` always returns undefined. Check `(() => {})()` in console

https://github.com/Fafruch/kalkulator-agh/blob/master/src/utils/pointsCalculator.js
Go for `switch` statement

https://github.com/Fafruch/kalkulator-agh/blob/master/server/main.js
You dont need additional setup to just serve build with HMR. Consider [webpack dev server](https://webpack.github.io/docs/webpack-dev-server.html) next time

**Comment by Fafruch** [comment]
1. Good point, I'll change that
2. Ok, to do
3. I changed them to absolute paths, but then again to relative paths. What's wrong with them?
4. Right!
5. How's about these semicolons? Airbnb plugin forces to use them, but I thought they're becoming extinct.
6. Will change that, thanks
7. I wanted these conditions to be more explicit, but if it is an anti-pattern, I will remove them :)
8. It was just for me, later I forgot about it, thanks
9. Good point :)
10. Not sure how should I declare this object. Without any properties and later just append them?
11. Ok!
12. Can you explain it further?
13. I lazily used ready for use boilerplate with HMR, next time I will try to manually customize eg. react-starter-kit

And many thanks for the review! :)
